apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-web-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /mnt/web/static-website